name: 'helmut.cloud catalog upload'
description: 'Upload a helmut.cloud node catalog to a S3 object storage'
author: 'MoovIT Software Products GmbH'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  endpoint:
    description: 'S3 object storage endpoint'
    required: true
  public_endpoint:
    description: 'S3 object storage public endpoint (read-only)'
    required: true
  region:
    description: 'S3 object storage region'
    required: false
    default: 'auto'
  bucket:
    description: 'S3 object storage bucket'
    required: true
  access_key_id:
    description: 'Access key ID for the S3 object storage'
    required: true
  secret_access_key:
    description: 'Secret Access key for the S3 object storage'
    required: true
  dest_dir:
    description: 'Destination directory in the object storage'
    required: true
  source_dir:
    description: 'Source directory to be uploaded'
    required: true
  name:
    description: 'Name of the catalog'
    required: true
  description:
    description: 'Description of the catalog'
    required: true
  logo:
    description: 'URL to the logo of the catalog'
    required: true
  version:
    description: 'Version of the new catalog'
    required: true
  minimum_engine_version:
    description: 'Minimum engine version the catalog requires'
    required: true
  on_fail:
    description:
      'Action to take on cleanup on the upload fails. Use "delete" or leave
      empty'
    required: false

# Define your outputs here.
outputs:
  url:
    description: 'URL that can be used to add the catalog to a space'

runs:
  using: node20
  main: dist/index.js
